### ISSUE TITLE
Unit tests failing due to Styled-Components

### ISSUE THREAD

**Issue by Nayshlok** [WTW-IM/es-components#152]
The snapshots seem to be failing now because the styledcomponent names are more random. Because the snapshot includes them and they are being generated each time we can't get a passing build.

**Comment by aabenoja** [comment]
This doesn't appear to be an issue. The latest master is building just fine. I pushed up a [copy of your branch](https://github.com/WTW-IM/es-components/compare/tabPanelTest) with a [revert of your snapshot updates](https://github.com/WTW-IM/es-components/commit/ddb7d12b5629480f5ddd3fe062390dc811072940). Since the build is [passing](https://travis-ci.org/WTW-IM/es-components/builds/371196392) I'm pretty sure this is a non issue and can be safely closed.

We're currently locked to [`styled-components@^2.4.0`](https://github.com/styled-components/styled-components/releases/tag/v2.4.0), which was released back in January and they're currently on `v3.2.6`, so we can rule out a version mismatch unless you were somehow on an older version. I don't know what else could have caused your hiccup.

Feel free to reopen once you've found more info.
