### ISSUE TITLE
Navigation components are not flexible

### ISSUE THREAD

**Issue by jrios** [WTW-IM/es-components#261]
Right now, Navigation components are forcing the hand of downstream projects to conform to its requirements.

For example, if I wanted to use a client side router with the SideNav/HorizontalNav components, I don't have a very easy way to do that.

It would be nice to be able to have an API like this:

```jsx
<SideNav>
    <NavItem>
      <a href="http://google.com">Google</a>
    </NavItem>
    <NavItem>
      <button>Do something</button>
    </NavItem>
    <NavItem>
      <Link to="/shopping-cart">Shopping Cart</Link>
    </NavItem>
</SideNav>
```

And all the styles get propagated appropriately, but downstream users have control of what goes in each NavItem. Thoughts? @Darrken

**Comment by Darrken** [comment]
I think we could simplify them to support that kind of API pretty easily. There isn't much use to having it maintain its own state as it does now, and we could change it so you could just set the `active` and `disabled` items with an attribute.

**Comment by Darrken** [comment]
This has ended up being tougher than I thought. Mainly because the styles are currently focused on anchor tags within the list items, with the arrow icons being siblings to the anchors. Not a big deal, but will take some rework.

The other thing I'm having trouble thinking through is how state can be managed if we don't include `id` on items. Is there an easy way to shift an `active` prop from one NavItem to another assuming we go by your example above?

**Comment by sbartlett** [comment]
You did it 👍
